service: create-ticket

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  include:
    handler.ts

functions:
  createTicket:
    handler: src/main/handler/Handler.createTicket

    events:
      - http:
          path: /ticket
          method: post