service: create-client

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  include:
    handler.ts

functions:
  createClient:
    handler: src/main/handler/Handler.createClient

    events:
      - http:
          path: /client
          method: post
  signin:
    handler: src/main/handler/HandlerSignin.signin

    events:
      - http:
          path: /signin
          method: post        