service: search-client

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  include:
    handler.ts

functions:
  searchClient:
    handler: src/main/handler/Handler.searchClient

    events:
      - http:
          path: /client/{id}
          method: get